version: '3.1'

services:
  cwskimmer_persistence:
    image: ghcr.io/8ch9azbsfifz/cwskimmer_persistence:latest
    restart: always
    environment:
      ENV DB_HOST: "localhost"
      ENV DB_PORT: "27017"
      ENV DB_USER: "root"
      ENV DB_PASS: "secure"
      ENV DB_NAME: "cwskimmer"

      ENV SKIMMER_HOST: "localhost"
      ENV SKIMMER_PORT: "7301"
      ENV SKIMMER_USER: "DB2CW"
      ENV SKIMMER_PASS: ""
