version: '3.1'

services:
  cwskimmer_persistence:
    image: ghcr.io/8ch9azbsfifz/cwskimmer_persistence:latest
    restart: always
    environment:
      DB_HOST: "localhost"
      DB_PORT: "27017"
      DB_USER: "root"
      DB_PASS: "secure"
      DB_NAME: "cwskimmer"

      SKIMMER_HOST: "localhost"
      SKIMMER_PORT: "7301"
      SKIMMER_USER: "DB2CW"
      SKIMMER_PASS: ""
